# Generated by Django 3.2.18 on 2023-02-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDialogPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(default='0', max_length=200, verbose_name='Conversation ID')),
                ('type', models.CharField(choices=[('question', 'question'), ('answer', 'answer'), ('additional_answer', 'additional answer'), ('result_evaluation', 'result evaluation')], default='question', max_length=30, verbose_name='Messege type')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Messege content')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name='Additional information')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Dialog messages',
                'db_table': 'DialogPositions',
            },
        ),
    ]
